from flask import Flask, request, jsonify
import pandas as pd
import pickle

app = Flask(__name__)

# Load the trained model
try:
    # Ensure the filename matches what was generated by your training script
    with open('fertilizer_model.pkl', 'rb') as f:
        model = pickle.load(f)
except FileNotFoundError:
    model = None

@app.route('/', methods=['GET'])
def home():
    if model is None:
        return jsonify({"status": "error", "message": "Model not found. Please upload fertilizer_model.pkl"}), 500
    return jsonify({"status": "healthy", "message": "Fertilizer Prediction API is running. Send POST request to /predict"})

@app.route('/predict', methods=['POST'])
def predict():
    if model is None:
        return jsonify({"error": "Model not loaded"}), 500
    
    try:
        # Handle both JSON and Form data
        if request.is_json:
            data = request.get_json()
        else:
            data = request.form.to_dict()

        # Validate and prepare input data
        # Using .get() with defaults to prevent errors if keys are missing
        input_data = {
            'Temparature': [int(data.get('Temparature'))],
            'Humidity': [int(data.get('Humidity'))],
            'Moisture': [int(data.get('Moisture'))],
            'Soil Type': [data.get('Soil Type')],
            'Crop Type': [data.get('Crop Type')],
            'Nitrogen': [int(data.get('Nitrogen'))],
            'Potassium': [int(data.get('Potassium'))],
            'Phosphorous': [int(data.get('Phosphorous'))]
        }
        
        # Create DataFrame for the model
        input_df = pd.DataFrame(input_data)
        
        # Make prediction
        prediction = model.predict(input_df)[0]
        
        return jsonify({
            "success": True,
            "prediction": prediction
        })

    except ValueError as e:
        return jsonify({"success": False, "error": "Invalid input type. Please ensure numbers are provided for numeric fields.", "details": str(e)}), 400
    except TypeError as e:
        return jsonify({"success": False, "error": "Missing required fields.", "details": str(e)}), 400
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)
